<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '2.5" HDD' => '',
    '3.5" HDD' => '',
    'Brand' => 'Бренд',
    'Bulk actions' => 'Балковые действия',
    'Bulk move' => 'Балковое перемещение',
    'CPU quantity' => 'количество CPU',
    'CPU sockets' => 'сокеты CPU',
    'Config Templates' => 'Шаблоны конфигурации',
    'Copy' => 'Скопировать',
    'Copy Part' => 'Копирование детали',
    'Create Part' => 'Создание детали',
    'Created range' => 'Созданный диапазон',
    'DC ticket' => 'DC тикет',
    'DCS' => '',
    'Data' => 'Данные',
    'Description' => 'Описание',
    'Destination' => 'Куда',
    'Failed set serial' => 'Не удалось установить серийные номера',
    'Form factor' => 'Форм-фактор',
    'Group' => 'Группа',
    'Hide from users' => 'Спрятать от пользователей',
    'History' => 'История',
    'Last move' => 'Последнее перемещение',
    'Last price' => 'Последняя цена',
    'Location' => 'Позиция',
    'Manufacturer' => 'Производитель',
    'Manufacturers' => 'Производители',
    'Max RAM' => 'Макс. RAM',
    'Model' => 'Модель',
    'Model details' => 'Информаци о модели',
    'Model has been created' => 'Модель создана',
    'Model has been updated' => 'Модель изменена',
    'Model types' => '',
    'Models' => 'Модели',
    'Models have been marked' => 'Модели помечены',
    'Move' => 'Перемещение',
    'Moved' => 'Перемещён',
    'Move by one' => 'Перемещение по одному',
    'Move description' => 'Описание перемещения',
    'Move history' => 'История перемещений ',
    'Move type' => 'Тип перемещения',
    'Moves' => 'Перемещения',
    'NL Amsterdam M3' => '',
    'NL Amsterdam SDG' => '',
    'Order' => 'Заказ',
    'Order No.' => 'Номер заказа',
    'Part No.' => 'Артикул',
    'Part has been created' => 'Деталь создана',
    'Part has been updated' => 'Деталь изменена',
    'Parts' => 'Детали',
    'Parts have been moved' => 'Детали перемещены',
    'Parts have been updated' => '',
    'Parts in move' => 'Парты в перемещении',
    'Price changed' => 'Цена изменена',
    'RAM slots' => 'Слотов оперативной памяти',
    'RAM volume' => 'Объем оперативной памяти',
    'RMA' => '',
    'Repair' => 'Восстановление',
    'Repair parts' => 'Восстановление деталей',
    'Replace' => 'Замена',
    'Reserve' => 'Резерв',
    'Serial' => 'Серийный номер',
    'Serial updated' => 'Серийные номера установлены',
    'Serials' => 'Серийные номера',
    'Set price' => 'Установить цену',
    'Set serial' => 'Установить серийные номера',
    'Short' => 'Короткое описание',
    'Show for users' => 'Показать пользователям',
    'Show hidden' => 'Отображать скрытые',
    'Source' => 'Откуда',
    'Stock' => 'Склад',
    'Supplier' => 'Поставщик',
    'TOTAL' => 'ИТОГО',
    'Tags' => 'Теги',
    'Trash' => 'Выбросить',
    'Type' => 'Тип',
    'USA Equinix DC10' => '',
    'Units' => 'Юниты',
    'Unreserve' => 'Разрезервировать',
    'Update' => 'Редактировать',
    'Валюта' => '',
    'Модель' => '',
];
